#! /bin/sh

# config options
bspc config border_width            1
bspc config top_padding             22
bspc config window_gap              10
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config auto_cancel             true

# desktops
# bspc monitor -d main web term misc foo
# below icons from siji
bspc monitor -d     

bspc desktop ^2 -l monocle

# Rules
bspc rule -a Firefox desktop=^2
bspc rule -a Gimp-2.8 desktop=^4 floating=on
bspc rule -a Gimp desktop=^4 floating=on
bspc rule -a deadbeef floating=on
bspc rule -a playlist floating=on
bspc rule -a transmission-gtk desktop=^5
bspc rule -a lxappearance floating=on center=true
bspc rule -a nitrogen floating=on center=true
bspc rule -a file-roller floating=on center=true

# colors
bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#6C6C6C"
bspc config active_border_color "#6C6C6C"
bspc config focused_locked_border_color "#00C7D8"
bspc config normal_locked_border_color "#6C6C6C"
bspc config active_locked_border_color "#6C6C6C"
bspc config urgent_border_color "#CB4B16"
bspc config presel_border_color "#ee6666"

# Autostart apps
compton &
nitrogen --restore
mpd &
numlockx &
xsetroot -cursor_name left_ptr
bspwm_panel.sh &

