#! /bin/sh

# config options
bspc config border_width            2
bspc config top_padding             32
bspc config window_gap              15
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config auto_cancel             true

# desktops
# bspc monitor -d main web term misc foo
bspc monitor -d 1 2 3 4 5

bspc desktop ^2 -l monocle

# Rules
bspc rule -a Firefox desktop=^2
bspc rule -a Gimp-2.8 desktop=^4 floating=on
bspc rule -a Gimp desktop=^4 floating=on
bspc rule -a deadbeef floating=on
bspc rule -a transmission-gtk desktop=^5
bspc rule -a lxappearance floating=on center=true
bspc rule -a nitrogen floating=on center=true
bspc rule -a file-roller floating=on center=true

# colors
# source the theme colors
source ~/.scripts/theme_config
# use the defined colors
bspc config focused_border_color ${focused_border_color}
bspc config normal_border_color ${normal_border_color}
bspc config active_border_color ${active_border_color}
bspc config focused_locked_border_color ${focused_locked_border_color}
bspc config normal_locked_border_color ${normal_locked_border_color}
bspc config active_locked_border_color ${active_locked_border_color}
bspc config urgent_border_color ${urgent_border_color}
bspc config presel_border_color ${presel_border_color}

# Autostart apps
compton &
nitrogen --restore
mpd &
numlockx &
xsetroot -cursor_name left_ptr
bspwm_panel.sh &

