#! /bin/sh

. ~/.scripts/theme_config

# config options
bspc config border_width            3
bspc config top_padding             $PANEL_HEIGHT
bspc config window_gap              15
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config click_to_focus          true
bspc config initial_polarity        second_child # new split to the right

# desktops
bspc monitor -d main web term misc foo

# Rules
bspc desktop ^2 -l monocle
bspc rule -a Firefox desktop=^2
bspc rule -a Gimp desktop=^4
bspc rule -a Gimp-2.8 desktop=^4
bspc rule -a Transmission-gtk desktop=^5
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Nitrogen state=floating center=true
bspc rule -a File-roller state=floating center=true
bspc rule -a keepassxc state=floating
bspc rule -a scratchpad state=floating hidden=on sticky=on locked=on

# colors
bspc config focused_border_color ${focused_border_color}
bspc config normal_border_color ${normal_border_color}
bspc config active_border_color ${active_border_color}
bspc config presel_feedback_color ${presel_color}

# Autostart apps
xsetroot -cursor_name left_ptr
numlock.sh &
compton &
nitrogen --restore
panel.sh &
firefox -private-window &
scratchpad.sh launch &


