#!/bin/bash

# Edited for August desktop. See panel config and termcolors.

#FONT="tamsynmod:pixelsize=11"
FONT="-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1"
PAD='  '
ACT='onstart=uncollapse;button1=exit;button3=exit'
YPOS='20'
TIME='4'

# Colors
FG="#bbbbbb"
BG="#1a1a1a"

bar_bg="#444444"
bar_fg="#076580"
label="#00adca"
highlight="#00adca"
highlight2="#0a0a0a"
warn="#8f4051"

OPTIONS="-bg ${BG} -fg ${FG} -y ${YPOS} -e ${ACT} -ta 'c'"
