#!/bin/bash

# Edited for December desktop. See panel config and termcolors.

#FONT="tamsynmod:pixelsize=11"
FONT="-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1"
PAD='  '
ACT='onstart=uncollapse;button1=exit;button3=exit'
YPOS='20'
TIME='4'

# Colors
FG="#c0c0c0"
BG="#1d1f21"

bar_bg="#444444"
bar_fg="#8c9440"
label="#81a2be"
highlight="#81a2be"
highlight2="#0a0a0a"
warn="#CC6666"

OPTIONS="-bg ${BG} -fg ${FG} -y ${YPOS} -e ${ACT} -ta 'c'"

