#!/bin/bash

# Edited for May desktop. See panel config and termcolors.

FONT="tamsynmod:pixelsize=11"
#FONT="-benis-uushi-medium-r-normal--11-90-75-75-p-58-iso10646-1"
PAD='  '
ACT='onstart=uncollapse;button1=exit;button3=exit'
YPOS='25'
TIME='4'

# Colors
FG="#cccccc"
BG="#303030"

bar_bg="#555555"
bar_fg="#4169A6"
label="#C14474"
highlight="#E86969"
highlight2="#101010"
warn="#C5A03F"

 OPTIONS="-bg ${BG} -fg ${FG} -y ${YPOS} -e ${ACT} -ta 'c'"
